# Generated by Django 3.2.8 on 2022-08-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fi',
            name='date',
            field=models.TextField(),
        ),
    ]
