# Generated by Django 3.2.8 on 2022-08-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_auto_20220815_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fi',
            name='body',
        ),
        migrations.AddField(
            model_name='fi',
            name='a',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fi',
            name='b',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fi',
            name='c',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fi',
            name='d',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fi',
            name='e',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='fi',
            name='f',
            field=models.TextField(default=''),
        ),
    ]
